<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'lexik_form_filter.data_extraction_method.default' shared service.

include_once $this->targetDirs[3].'/vendor/lexik/form-filter-bundle/Filter/DataExtractor/Method/DataExtractionMethodInterface.php';
include_once $this->targetDirs[3].'/vendor/lexik/form-filter-bundle/Filter/DataExtractor/Method/DefaultExtractionMethod.php';

return $this->services['lexik_form_filter.data_extraction_method.default'] = new \Lexik\Bundle\FormFilterBundle\Filter\DataExtractor\Method\DefaultExtractionMethod();
