<?php

namespace AppBundle\Repository;

/**
 * ExpedienteAsociadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpedienteAsociadoRepository extends \Doctrine\ORM\EntityRepository
{
}
