<?php

namespace AppBundle\Repository;

/**
 * MovimientoExpedienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientoExpedienteRepository extends \Doctrine\ORM\EntityRepository
{
}
