<?php

namespace AppBundle\Repository;

/**
 * ResolucionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResolucionRepository extends \Doctrine\ORM\EntityRepository
{
}
