<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'app.util' shared autowired service.

include_once $this->targetDirs[3].'/src/AppBundle/Services/Util.php';

return $this->services['app.util'] = new \AppBundle\Services\Util('null');
