<?php

namespace AppBundle\Repository;

/**
 * CaratulaAgregadaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaratulaAgregadaRepository extends \Doctrine\ORM\EntityRepository {

    public function createCaratulaFilterQuery($expediente) {
        $qb = $this->getEntityManager()->createQueryBuilder('c');
        $result = $qb->select('c')
                ->from('AppBundle:CaratulaAgregada', 'c')
                ->innerJoin(\AppBundle\Entity\Expediente::class, "e", "WITH",
                        "c.expediente=e.id")
                ->innerJoin(\AppBundle\Entity\Tema::class, "t", "WITH",
                        "c.tema=t.id")
                ->where('e.id = :expediente')
                ->setParameter('expediente', $expediente);

        return $result;
    }

}
