<?php

namespace AppBundle\Repository;

/**
 * CaratulaAgregadaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaratulaAgregadaRepository extends \Doctrine\ORM\EntityRepository
{
}
