<?php

namespace AppBundle\Repository;

/**
 * CaratulaAgregadaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaratulaAgregadaRepository extends \Doctrine\ORM\EntityRepository {

    public function createCaratulaFilterQuery($expediente) {
        $qb = $this->getEntityManager()->createQueryBuilder('c');
        $result = $qb->select('c')
                ->from('AppBundle:CaratulaAgregada', 'c')
                ->innerJoin(\AppBundle\Entity\Expediente::class, "e", "WITH", "c.expediente=e.id")
                ->innerJoin(\AppBundle\Entity\Tema::class, "t", "WITH", "c.tema=t.id")
                ->where('c.fechaBaja IS NULL')
                ->andWhere('e.id = :expediente')
                ->setParameter('expediente', $expediente);

        return $result;
    }

    public function findByCaratula($caratula) {
        $qb = $this->getEntityManager()->createQueryBuilder('c');
        $result = $qb->select('c')
                ->from(\AppBundle\Entity\CaratulaAgregada::class, 'c')
                ->where('c.id = :caratula')
                ->andWhere('c.fechaBaja IS NULL')
                ->setParameter('caratula', $caratula);
        $caratula = $result->getQuery()->getResult();
        if (count($caratula) > 0) {
            return $caratula[0];
        } else {
            return null;
        }
    }

}
