<?php

namespace AppBundle\Repository;

/**
 * CaratulaRegistroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaratulaRegistroRepository extends \Doctrine\ORM\EntityRepository
{
}
