<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * DependenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DependenciaRepository extends \Doctrine\ORM\EntityRepository {
    
       public function createDependenciaFilter() {
        $qb = $this->getEntityManager()->createQueryBuilder('d');
        $result = $qb->select('d')
                ->from(\AppBundle\Entity\Dependencia::class, 'd')
                ->addOrderBy('d.descripcion', 'ASC');
        
        return $result;
    }  

}
