<?php

namespace AppBundle\Repository;

/**
 * DependenciaRegistroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DependenciaRegistroRepository extends \Doctrine\ORM\EntityRepository
{
}
