<?php

namespace AppBundle\Repository;

/**
 * DependenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DependenciaRepository extends \Doctrine\ORM\EntityRepository {

    public function createDependenciaFilter() {
        $qb = $this->getEntityManager()->createQueryBuilder('d');
        $result = $qb->select('d')
                ->from(\AppBundle\Entity\Dependencia::class, 'd')
                ->where('d.fechaBaja IS NULL')
                ->addOrderBy('d.descripcion', 'ASC');

        return $result;
    }

    public function findByDependencia($dependencia) {
        $qb = $this->getEntityManager()->createQueryBuilder('d');
        $result = $qb->select('d')
                ->from(\AppBundle\Entity\Dependencia::class, 'd')
                ->where('d.id = :dependencia')
                ->andWhere('d.fechaBaja IS NULL')
                ->setParameter('dependencia', $dependencia);

        $dependencia = $result->getQuery()->getResult();
        if (count($dependencia) > 0) {
            return $dependencia[0];
        } else {
            return null;
        }
    }

}
