<?php

namespace AppBundle\Repository;

/**
 * ExpedienteAsociadoRegistroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpedienteAsociadoRegistroRepository extends \Doctrine\ORM\EntityRepository
{
}
