<?php

namespace AppBundle\Repository;

/**
 * ExpedienteRegistroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpedienteRegistroRepository extends \Doctrine\ORM\EntityRepository
{
}
