<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ExpedienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpedienteRepository extends \Doctrine\ORM\EntityRepository
{
    
     public function getAllPers($currentPage = 1, $limit = 15)
    {
          
        $em = $this->getEntityManager();
        
        $dql= "SELECT e FROM AppBundle\Entity\Expediente e ORDER BY e.id";

        $query = $em->createQuery($dql)
                ->setFirstResult($limit*($currentPage-1))
                ->setMaxResults($limit);


        $paginator = new Paginator($query, $fetchJoinCollection=true);

        return $paginator;
    }
    
    
}
