<?php

namespace AppBundle\Repository;

/**
 * ExpedienteAsociadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpedienteAsociadoRepository extends \Doctrine\ORM\EntityRepository
{
     public function createAsociadoFilterQuery($expediente) {
        $qb = $this->getEntityManager()->createQueryBuilder('ea');
        $result = $qb->select('ea')
                ->from('AppBundle:ExpedienteAsociado', 'ea')
                ->innerJoin(\AppBundle\Entity\Expediente::class, "e", "WITH",
                        "ea.expedienteAsociado=e.id")
                ->innerJoin(\AppBundle\Entity\Tema::class, "t", "WITH",
                        "e.tema=t.id")
                ->where('ea.fechaBaja IS NULL')
                ->andWhere("ea.expedientePadre = :expediente_padre")
                ->setParameter('expediente_padre',$expediente);

        return $result;
    }
    
        public function findByAsociado($asociado){       
        $qb = $this->getEntityManager()->createQueryBuilder('ea');
        $result = $qb->select('ea')
                ->from(\AppBundle\Entity\ExpedienteAsociado::class, 'ea')
                ->where('ea.id = :asociado')
                ->andWhere('ea.fechaBaja IS NULL')
                ->setParameter('asociado', $asociado);
        $exp_asociado = $result->getQuery()->getResult();
        return $exp_asociado[0];       
    }
    
}
