<?php

namespace AppBundle\Repository;

/**
 * LugarFisicoRegistroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LugarFisicoRegistroRepository extends \Doctrine\ORM\EntityRepository
{
}
