<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * LugarFisicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LugarFisicoRepository extends \Doctrine\ORM\EntityRepository {

    public function createLugarFilter($user) {
        $qb = $this->getEntityManager()->createQueryBuilder('l');
        $result = $qb->select('l')
                ->from('AppBundle:LugarFisico', 'l');
        if ($user->getRole() != "ROLE_ADMIN") {
            $result
                    ->innerJoin(\AppBundle\Entity\Ubicacion::class, "u", "WITH",
                            "l.id = u.id")
                    ->where('l.dependencia= :dependencia')
                    ->setParameter('dependencia', $user->getPersona()->getDependencia());
        } else {
            $result
                    ->innerJoin(\AppBundle\Entity\Ubicacion::class, "u", "WITH",
                            "l.id = u.id")
                    ->innerJoin(\AppBundle\Entity\Dependencia::class, "d", "WITH",
                            "l.dependencia = d.id");
        }

        return $result;
    }

}
