<?php

namespace AppBundle\Repository;

/**
 * MesaEntradaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MesaEntradaRepository extends \Doctrine\ORM\EntityRepository
{
}
