<?php

namespace AppBundle\Repository;

/**
 * MesaEntradaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MesaEntradaRepository extends \Doctrine\ORM\EntityRepository {
    
     public function createMesaentradaFilter() {
        $qb = $this->getEntityManager()->createQueryBuilder('m');
        $result = $qb->select('m')
                ->from(\AppBundle\Entity\MesaEntrada::class, 'm')
                ->innerJoin(\AppBundle\Entity\Ubicacion::class, "u", "WITH", "m.id=u.id")
                ->innerJoin(\AppBundle\Entity\Dependencia::class, "d", "WITH", "u.dependencia=d.id")
                ->where('u.fechaBaja IS NULL');
        return $result;
    }
    
    public function findByMesaentrada($mesaentrada) {
        $qb = $this->getEntityManager()->createQueryBuilder('m');
        $result = $qb->select('m')
                ->from(\AppBundle\Entity\MesaEntrada::class, 'm')
                ->innerJoin(\AppBundle\Entity\Ubicacion::class, "u", "WITH", "m.id=u.id")
                ->where('m.id = :mesaentrada')
                ->andWhere('u.fechaBaja IS NULL')
                ->setParameter('mesaentrada', $mesaentrada);

        $mesaentrada = $result->getQuery()->getResult();
         if (count($mesaentrada) > 0) {
            return $mesaentrada[0];
        } else {
            return null;
        }
    }

}
