<?php

namespace AppBundle\Repository;

/**
 * MesaEntradaRegistroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MesaEntradaRegistroRepository extends \Doctrine\ORM\EntityRepository
{
}
