<?php

namespace AppBundle\Repository;

/**
 * MovimientoRegistroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientoRegistroRepository extends \Doctrine\ORM\EntityRepository
{
}
