<?php

namespace AppBundle\Repository;

/**
 * MovimientoExpedienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientoExpedienteRepository extends \Doctrine\ORM\EntityRepository {

    public function createMovimientoFilter($expediente) {
        $qb = $this->getEntityManager()->createQueryBuilder('m');
        $result = $qb->select('m')
                ->from(\AppBundle\Entity\MovimientoExpediente::class, 'm')
                ->leftJoin(\AppBundle\Entity\Expediente::class, "e", "WITH", "m.expediente = e.id")
                ->where('m.expediente = :expediente')
                ->andWhere('m.fechaBaja IS NULL')
                ->setParameter('expediente', $expediente);

        return $result;
    }

    public function findByMovimiento($movimiento) {
        $qb = $this->getEntityManager()->createQueryBuilder('m');
        $result = $qb->select('m')
                ->from(\AppBundle\Entity\MovimientoExpediente::class, 'm')
                ->where('m.id = :movimiento')
                ->andWhere('m.fechaBaja IS NULL')
                ->setParameter('movimiento', $movimiento);
        $movimiento = $result->getQuery()->getResult();
        if (count($movimiento) > 0) {
            return $movimiento[0];
        } else {
            return null;
        }
    }

}
