<?php

namespace AppBundle\Repository;

/**
 * MovimientoExpedienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientoExpedienteRepository extends \Doctrine\ORM\EntityRepository {

    public function createMovimientoFilter($expediente) {
        $qb = $this->getEntityManager()->createQueryBuilder('m');
        $result = $qb->select('m')
                ->from(\AppBundle\Entity\MovimientoExpediente::class, 'm')
                ->leftJoin(\AppBundle\Entity\Expediente::class, "e", "WITH", "m.expediente = e.id")
                ->where('m.expediente = :expediente')
//                                ->andWhere('w.id != :expediente_id')
                ->setParameter('expediente', $expediente);

        return $result;
    }

}
