<?php

namespace AppBundle\Repository;

/**
 * PersonaRegistroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonaRegistroRepository extends \Doctrine\ORM\EntityRepository
{
}
