<?php

namespace AppBundle\Repository;

/**
 * ResolucionRegistroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResolucionRegistroRepository extends \Doctrine\ORM\EntityRepository
{
}
