<?php

namespace AppBundle\Repository;

/**
 * ResolucionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResolucionRepository extends \Doctrine\ORM\EntityRepository {

    public function findByResolucion($resolucion) {
        $qb = $this->getEntityManager()->createQueryBuilder('r');
        $result = $qb->select('r')
                ->from(\AppBundle\Entity\Resolucion::class, 'r')
                ->where('r.id = :resolucion')
                ->andWhere('r.fechaBaja IS NULL')
                ->setParameter('resolucion', $resolucion);
        $resolucion_resu = $result->getQuery()->getResult();
        if (count($resolucion_resu) > 0) {
            return $resolucion_resu[0];
        } else {
            return null;
        }
    }

}
