<?php

namespace AppBundle\Repository;

/**
 * TemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemaRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLikeName($term) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $result = $qb->select('n')
                ->from('AppBundle:Tema', 'n')
                ->where($qb->expr()
                        ->like('n.codigo', $qb->expr()
                                ->literal('%' . $term . '%')))
                ->setMaxResults(10)->getQuery()->getResult();
        return $result;
    }

}
