<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends \Doctrine\ORM\EntityRepository {

    public function findLikeName($term) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $result = $qb->select('n')
                        ->from('AppBundle:Usuario', 'n')
                        ->where($qb->expr()
                                ->like('n.iup', $qb->expr()
                                        ->literal('%' . $term . '%')))
                        ->setMaxResults(10)->getQuery()->getResult();
        return $result;
    }

    public function createUsuarioFilter() {
        $qb = $this->getEntityManager()->createQueryBuilder('u');
        $result = $qb->select('u')
                ->from(\AppBundle\Entity\Usuario::class, 'u')
                ->innerJoin(\AppBundle\Entity\Persona::class, "p", "WITH",
                        "u.persona=p.id")    
                ->innerJoin(\AppBundle\Entity\Ubicacion::class, "ub", "WITH",
                        "p.id=ub.id")
                ->innerJoin(\AppBundle\Entity\Dependencia::class, "d", "WITH",
                        "ub.dependencia=d.id")
                ->addOrderBy('u.iup', 'ASC');

        return $result;
    }

}
