<?php

namespace AppBundle\Repository;

/**
 * UsuarioRegistroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRegistroRepository extends \Doctrine\ORM\EntityRepository
{
}
