# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    access_denied_url: /expediente/listado/1
    
    encoders:
        AppBundle\Entity\Usuario:
            algorithm: bcrypt
            cost: 4
    

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            chain:
                providers: [db_username, db_email]
        db_username:
            entity:
                class: AppBundle:Usuario
                property: iup
        db_email:
            entity:
                class: AppBundle:Usuario
                property: email        
                
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: our_db_provider
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout
                target: /login
                
                
    role_hierarchy:
        ROLE_ADMIN: [ROLE_RESPONSABLE,ROLE_USER]
                
    #Control de acceso para Usuarios            
    access_control:        
        - {path : ^/add/expediente, roles: [ROLE_RESPONSABLE] }
        - {path : ^/listaExpediente, roles: [ROLE_USER,ROLE_RESPONSABLE] }
        - {path : ^/expediente/editar/, roles:[ROLE_RESPONSABLE,ROLE_USER]}
        - {path : ^/expediente/delete/, roles:[ROLE_RESPONSABLE,ROLE_USER]}
        - {path : ^/expediente/add/caratulaAgregada/, roles:[ROLE_RESPONSABLE,ROLE_USER]}
        - {path : ^/expediente/delete_caratula/, roles:[ROLE_RESPONSABLE,ROLE_USER]}
        - {path : ^/expediente//caratula/listado/, roles:[ROLE_RESPONSABLE,ROLE_USER]}
        - {path : ^/expediente/ver_caratula/, roles:[ROLE_RESPONSABLE,ROLE_USER]}
        
        - {path : ^/expediente/add/movimiento, roles:[ROLE_RESPONSABLE,ROLE_USER]}
        - {path : ^/expediente/movimiento/editar/, roles:[ROLE_RESPONSABLE,ROLE_USER]}  
        - {path : ^/expediente/resolucion/, roles:[ROLE_RESPONSABLE,ROLE_USER]}
        - {path : ^/expediente/resolucion/detalle/, roles:[ROLE_RESPONSABLE,ROLE_USER]}
       
        - {path : ^/usuario/listado/, roles:[ROLE_ADMIN] }   
        - {path : ^/usuario/add, roles:[ROLE_ADMIN] }
        - {path : ^/usuario/delete/, roles:[ROLE_ADMIN] }

        - {path : ^/dependencia/, roles:[ROLE_ADMIN] }
        
        - {path : ^/adm/gestionar/mesa_entrada/, roles:[ROLE_ADMIN] }
        
        
        - {path : ^/persona/listado/, roles:[ROLE_ADMIN] }
        - {path : ^/persona/add, roles:[ROLE_ADMIN] }
        - {path : ^/persona/delete/, roles:[ROLE_ADMIN] }
        - {path : ^/persona/edit/, roles:[ROLE_RESPONSABLE,ROLE_USER] }
        - {path : ^/gestionar/persona_responsbles/, roles:[ROLE_RESPONSABLE,ROLE_USER] }
       
        - {path : ^/lugar_fisico/edit/, roles:[ROLE_RESPONSABLE,ROLE_USER] }
        - {path : ^/lugar_fisico/add, roles:[ROLE_RESPONSABLE,ROLE_USER] }
        - {path : ^/gestionar/lugarfisico_responsables/, roles:[ROLE_RESPONSABLE,ROLE_USER] }
        
        
       

            # activate different ways to authenticate
    
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
