# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\Usuario:
            algorithm: bcrypt
            cost: 4
    

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            chain:
                providers: [db_username, db_email]
        db_username:
            entity:
                class: AppBundle:Usuario
                property: iup
        db_email:
            entity:
                class: AppBundle:Usuario
                property: email        
                
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: our_db_provider
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout
                target: /login
                
                
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER,ROLE_RESPONSABLE]
                
    #Control de acceso para Usuarios            
    access_control:
#        - {path : ^/home, roles: ROLE_USER }
        - {path : ^/listaExpediente, roles: [ROLE_USER,ROLE_RESPONSABLE] }
        - {path : ^/add/expediente, roles: [ROLE_RESPONSABLE] }
        - {path : ^/expediente, roles:[ROLE_USER,ROLE_RESPONSABLE] }
        - {path : ^/usuario/listado/, roles:[ROLE_ADMIN] }
        #no anda Editar expediente:
        - {path : ^/expediente/editar/, roles:[ROLE_ADMIN]}
        #no anda Movimiento exp:
        - {path : ^/expediente/editar/[id]/add/movimiento, roles:[ROLE_ADMIN]}
        - {path : ^/expediente/delete/, roles:[ROLE_ADMIN]}
        #no anda add caratula agregada: 
        - {path : ^/expediente/add/caratulaAgregada/, roles:[ROLE_ADMIN]}
        #no anda add movimiento: 
        - {path : ^/expediente/[id]/add/movimiento, roles:[ROLE_ADMIN]}
        #no anda add movimiento: 
        - {path : ^/expediente/[id]/resolucion, roles:[ROLE_ADMIN]}
        - {path : ^/dependencia/, roles:[ROLE_ADMIN] }
        - {path : ^/adm/gestionar/mesa_entrada/, roles:[ROLE_ADMIN] }
        - {path : ^/persona/, roles:[ROLE_ADMIN] }
        - {path : ^/adm/gestionar/persona_responsbles/, roles:[ROLE_ADMIN] }
        - {path : ^/lugar_fisico/edit/, roles:[ROLE_ADMIN] }
        - {path : ^/lugar_fisico/add, roles:[ROLE_ADMIN] }
        - {path : ^/adm/gestionar/lugarfisico_responsables/, roles:[ROLE_ADMIN] }
        
        
       

            # activate different ways to authenticate
    
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
