<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Dependencia extends \AppBundle\Entity\Dependencia implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Dependencia' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Dependencia' . "\0" . 'descripcion', '' . "\0" . 'AppBundle\\Entity\\Dependencia' . "\0" . 'dependenciaPadre', '' . "\0" . 'AppBundle\\Entity\\Dependencia' . "\0" . 'responsable', '' . "\0" . 'AppBundle\\Entity\\Dependencia' . "\0" . 'nivel', '' . "\0" . 'AppBundle\\Entity\\Dependencia' . "\0" . 'expedientes', '' . "\0" . 'AppBundle\\Entity\\Dependencia' . "\0" . 'ubicaciones', 'fechaBaja', '' . "\0" . 'AppBundle\\Entity\\Dependencia' . "\0" . 'fechaAlta', '' . "\0" . 'AppBundle\\Entity\\Dependencia' . "\0" . 'fechaUltimaModificacion', '' . "\0" . 'AppBundle\\Entity\\Dependencia' . "\0" . 'usuarioUltimaModificacion', '' . "\0" . 'AppBundle\\Entity\\Dependencia' . "\0" . 'mesaentrada', 'persona'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Dependencia' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Dependencia' . "\0" . 'descripcion', '' . "\0" . 'AppBundle\\Entity\\Dependencia' . "\0" . 'dependenciaPadre', '' . "\0" . 'AppBundle\\Entity\\Dependencia' . "\0" . 'responsable', '' . "\0" . 'AppBundle\\Entity\\Dependencia' . "\0" . 'nivel', '' . "\0" . 'AppBundle\\Entity\\Dependencia' . "\0" . 'expedientes', '' . "\0" . 'AppBundle\\Entity\\Dependencia' . "\0" . 'ubicaciones', 'fechaBaja', '' . "\0" . 'AppBundle\\Entity\\Dependencia' . "\0" . 'fechaAlta', '' . "\0" . 'AppBundle\\Entity\\Dependencia' . "\0" . 'fechaUltimaModificacion', '' . "\0" . 'AppBundle\\Entity\\Dependencia' . "\0" . 'usuarioUltimaModificacion', '' . "\0" . 'AppBundle\\Entity\\Dependencia' . "\0" . 'mesaentrada', 'persona'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Dependencia $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getMesaentrada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMesaentrada', []);

        return parent::getMesaentrada();
    }

    /**
     * {@inheritDoc}
     */
    public function setMesaentrada(\AppBundle\Entity\MesaEntrada $mesaentrada = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMesaentrada', [$mesaentrada]);

        return parent::setMesaentrada($mesaentrada);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersona()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersona', []);

        return parent::getPersona();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersona(\AppBundle\Entity\MesaEntrada $persona = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersona', [$persona]);

        return parent::setPersona($persona);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDependenciaPadre($dependenciaPadre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDependenciaPadre', [$dependenciaPadre]);

        return parent::setDependenciaPadre($dependenciaPadre);
    }

    /**
     * {@inheritDoc}
     */
    public function getDependenciaPadre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDependenciaPadre', []);

        return parent::getDependenciaPadre();
    }

    /**
     * {@inheritDoc}
     */
    public function setResponsable($responsable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResponsable', [$responsable]);

        return parent::setResponsable($responsable);
    }

    /**
     * {@inheritDoc}
     */
    public function getResponsable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResponsable', []);

        return parent::getResponsable();
    }

    /**
     * {@inheritDoc}
     */
    public function setNivel($nivel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNivel', [$nivel]);

        return parent::setNivel($nivel);
    }

    /**
     * {@inheritDoc}
     */
    public function getNivel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNivel', []);

        return parent::getNivel();
    }

    /**
     * {@inheritDoc}
     */
    public function addExpediente(\AppBundle\Entity\Expediente $expediente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addExpediente', [$expediente]);

        return parent::addExpediente($expediente);
    }

    /**
     * {@inheritDoc}
     */
    public function removeExpediente(\AppBundle\Entity\Expediente $expediente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeExpediente', [$expediente]);

        return parent::removeExpediente($expediente);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpedientes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpedientes', []);

        return parent::getExpedientes();
    }

    /**
     * {@inheritDoc}
     */
    public function addUbicacione(\AppBundle\Entity\Ubicacion $ubicacione)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUbicacione', [$ubicacione]);

        return parent::addUbicacione($ubicacione);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUbicacione(\AppBundle\Entity\Ubicacion $ubicacione)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUbicacione', [$ubicacione]);

        return parent::removeUbicacione($ubicacione);
    }

    /**
     * {@inheritDoc}
     */
    public function getUbicaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUbicaciones', []);

        return parent::getUbicaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setArchivado($archivado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArchivado', [$archivado]);

        return parent::setArchivado($archivado);
    }

    /**
     * {@inheritDoc}
     */
    public function getArchivado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArchivado', []);

        return parent::getArchivado();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaAlta($fechaAlta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaAlta', [$fechaAlta]);

        return parent::setFechaAlta($fechaAlta);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaAlta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaAlta', []);

        return parent::getFechaAlta();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaUltimaModificacion($fechaUltimaModificacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaUltimaModificacion', [$fechaUltimaModificacion]);

        return parent::setFechaUltimaModificacion($fechaUltimaModificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaUltimaModificacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaUltimaModificacion', []);

        return parent::getFechaUltimaModificacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioUltimaModificacion($usuarioUltimaModificacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioUltimaModificacion', [$usuarioUltimaModificacion]);

        return parent::setUsuarioUltimaModificacion($usuarioUltimaModificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioUltimaModificacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioUltimaModificacion', []);

        return parent::getUsuarioUltimaModificacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaBaja($fechaBaja)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaBaja', [$fechaBaja]);

        return parent::setFechaBaja($fechaBaja);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaBaja()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaBaja', []);

        return parent::getFechaBaja();
    }

}
