<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'lexik_form_filter.filter_prepare' shared service.

include_once $this->targetDirs[3].'/vendor/lexik/form-filter-bundle/Event/Listener/PrepareListener.php';

return $this->services['lexik_form_filter.filter_prepare'] = new \Lexik\Bundle\FormFilterBundle\Event\Listener\PrepareListener();
