<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'simplethings_entityaudit.log_revisions_listener' shared service.

include_once $this->targetDirs[3].'/vendor/doctrine/common/lib/Doctrine/Common/EventSubscriber.php';
include_once $this->targetDirs[3].'/vendor/simplethings/entity-audit-bundle/src/SimpleThings/EntityAudit/EventListener/LogRevisionsListener.php';

return $this->services['simplethings_entityaudit.log_revisions_listener'] = new \SimpleThings\EntityAudit\EventListener\LogRevisionsListener(${($_ = isset($this->services['simplethings_entityaudit.manager']) ? $this->services['simplethings_entityaudit.manager'] : $this->load('getSimplethingsEntityaudit_ManagerService.php')) && false ?: '_'});
