<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'simplethings_entityaudit.reader' shared service.

include_once $this->targetDirs[3].'/vendor/simplethings/entity-audit-bundle/src/SimpleThings/EntityAudit/AuditReader.php';

return $this->services['simplethings_entityaudit.reader'] = ${($_ = isset($this->services['simplethings_entityaudit.manager']) ? $this->services['simplethings_entityaudit.manager'] : $this->load('getSimplethingsEntityaudit_ManagerService.php')) && false ?: '_'}->createAuditReader(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'});
