<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'simplethings_entityaudit.manager' shared service.

include_once $this->targetDirs[3].'/vendor/simplethings/entity-audit-bundle/src/SimpleThings/EntityAudit/AuditManager.php';

return $this->services['simplethings_entityaudit.manager'] = new \SimpleThings\EntityAudit\AuditManager(${($_ = isset($this->services['simplethings_entityaudit.config']) ? $this->services['simplethings_entityaudit.config'] : $this->load('getSimplethingsEntityaudit_ConfigService.php')) && false ?: '_'});
