<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'simplethings_entityaudit.config' shared service.

include_once $this->targetDirs[3].'/vendor/simplethings/entity-audit-bundle/src/SimpleThings/EntityAudit/AuditConfiguration.php';
include_once $this->targetDirs[3].'/vendor/simplethings/entity-audit-bundle/src/SimpleThings/EntityAudit/User/TokenStorageUsernameCallable.php';

$this->services['simplethings_entityaudit.config'] = $instance = new \SimpleThings\EntityAudit\AuditConfiguration();

$instance->setAuditedEntityClasses($this->parameters['simplethings.entityaudit.audited_entities']);
$instance->setGlobalIgnoreColumns($this->parameters['simplethings.entityaudit.global_ignore_columns']);
$instance->setTablePrefix('');
$instance->setTableSuffix('_audit');
$instance->setRevisionTableName('revisions');
$instance->setRevisionIdFieldType('integer');
$instance->setRevisionFieldName('rev');
$instance->setRevisionTypeFieldName('revtype');
$instance->setUsernameCallable(${($_ = isset($this->services['simplethings_entityaudit.username_callable.token_storage']) ? $this->services['simplethings_entityaudit.username_callable.token_storage'] : ($this->services['simplethings_entityaudit.username_callable.token_storage'] = new \SimpleThings\EntityAudit\User\TokenStorageUsernameCallable($this))) && false ?: '_'});

return $instance;
