<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'simplethings_entityaudit.username_callable.token_storage' shared service.

include_once $this->targetDirs[3].'/vendor/simplethings/entity-audit-bundle/src/SimpleThings/EntityAudit/User/TokenStorageUsernameCallable.php';

return $this->services['simplethings_entityaudit.username_callable.token_storage'] = new \SimpleThings\EntityAudit\User\TokenStorageUsernameCallable($this);
