<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pugx_autocompleter.filter_autocomplete' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/AbstractType.php';
include_once $this->targetDirs[3].'/vendor/pugx/autocompleter-bundle/Form/Type/AutocompleteType.php';
include_once $this->targetDirs[3].'/vendor/pugx/autocompleter-bundle/Form/Type/AutocompleteFilterType.php';

return $this->services['pugx_autocompleter.filter_autocomplete'] = new \PUGX\AutocompleterBundle\Form\Type\AutocompleteFilterType(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
