<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDq4px8v\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDq4px8v/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDq4px8v.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDq4px8v\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerDq4px8v\appDevDebugProjectContainer([
    'container.build_hash' => 'Dq4px8v',
    'container.build_id' => '2af8dd4c',
    'container.build_time' => 1564138104,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDq4px8v');
