<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'lexik_form_filter.form_data_extractor' shared service.

include_once $this->targetDirs[3].'/vendor/lexik/form-filter-bundle/Filter/DataExtractor/FormDataExtractorInterface.php';
include_once $this->targetDirs[3].'/vendor/lexik/form-filter-bundle/Filter/DataExtractor/FormDataExtractor.php';
include_once $this->targetDirs[3].'/vendor/lexik/form-filter-bundle/Filter/DataExtractor/Method/DataExtractionMethodInterface.php';
include_once $this->targetDirs[3].'/vendor/lexik/form-filter-bundle/Filter/DataExtractor/Method/DefaultExtractionMethod.php';
include_once $this->targetDirs[3].'/vendor/lexik/form-filter-bundle/Filter/DataExtractor/Method/TextExtractionMethod.php';
include_once $this->targetDirs[3].'/vendor/lexik/form-filter-bundle/Filter/DataExtractor/Method/ValueKeysExtractionMethod.php';

$this->services['lexik_form_filter.form_data_extractor'] = $instance = new \Lexik\Bundle\FormFilterBundle\Filter\DataExtractor\FormDataExtractor();

$instance->addMethod(${($_ = isset($this->services['lexik_form_filter.data_extraction_method.default']) ? $this->services['lexik_form_filter.data_extraction_method.default'] : ($this->services['lexik_form_filter.data_extraction_method.default'] = new \Lexik\Bundle\FormFilterBundle\Filter\DataExtractor\Method\DefaultExtractionMethod())) && false ?: '_'});
$instance->addMethod(${($_ = isset($this->services['lexik_form_filter.data_extraction_method.text']) ? $this->services['lexik_form_filter.data_extraction_method.text'] : ($this->services['lexik_form_filter.data_extraction_method.text'] = new \Lexik\Bundle\FormFilterBundle\Filter\DataExtractor\Method\TextExtractionMethod())) && false ?: '_'});
$instance->addMethod(${($_ = isset($this->services['lexik_form_filter.data_extraction_method.key_values']) ? $this->services['lexik_form_filter.data_extraction_method.key_values'] : ($this->services['lexik_form_filter.data_extraction_method.key_values'] = new \Lexik\Bundle\FormFilterBundle\Filter\DataExtractor\Method\ValueKeysExtractionMethod())) && false ?: '_'});

return $instance;
