<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'lexik_form_filter.query_builder_updater' shared service.

include_once $this->targetDirs[3].'/vendor/lexik/form-filter-bundle/Filter/FilterBuilderUpdaterInterface.php';
include_once $this->targetDirs[3].'/vendor/lexik/form-filter-bundle/Filter/FilterBuilderUpdater.php';

return $this->services['lexik_form_filter.query_builder_updater'] = new \Lexik\Bundle\FormFilterBundle\Filter\FilterBuilderUpdater(${($_ = isset($this->services['lexik_form_filter.form_data_extractor']) ? $this->services['lexik_form_filter.form_data_extractor'] : $this->load('getLexikFormFilter_FormDataExtractorService.php')) && false ?: '_'}, ${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'});
