<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\Form\Event\Listener\AddStateFieldSubscriber' shared autowired service.

include_once $this->targetDirs[3].'/src/AppBundle/Form/Event/Listener/AddStateFieldSubscriber.php';

return $this->services['AppBundle\\Form\\Event\\Listener\\AddStateFieldSubscriber'] = new \AppBundle\Form\Event\Listener\AddStateFieldSubscriber();
