<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCcgo9a7\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCcgo9a7/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCcgo9a7.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCcgo9a7\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerCcgo9a7\appDevDebugProjectContainer([
    'container.build_hash' => 'Ccgo9a7',
    'container.build_id' => 'b32268e2',
    'container.build_time' => 1564058220,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCcgo9a7');
