<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4hvxvxj\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4hvxvxj/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container4hvxvxj.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container4hvxvxj\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container4hvxvxj\appDevDebugProjectContainer([
    'container.build_hash' => '4hvxvxj',
    'container.build_id' => 'fb72f07f',
    'container.build_time' => 1565793564,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4hvxvxj');
