<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOhvummy\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOhvummy/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOhvummy.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOhvummy\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerOhvummy\appDevDebugProjectContainer([
    'container.build_hash' => 'Ohvummy',
    'container.build_id' => '4e7037e0',
    'container.build_time' => 1566305482,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOhvummy');
